name: Deploy ZindaLearn Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            set -e
            APP_DIR="/var/www/zindalern-backend"

            mkdir -p $APP_DIR
            cd $APP_DIR

            if [ ! -d ".git" ]; then
              git clone git@github.com:job-zinda/zindalearnBackend.git .
            else
              git reset --hard
              git pull origin main
            fi

            npm install --production

            if pm2 list | grep -q "zindalern-server"; then
              pm2 restart zindalern-server
            else
              pm2 start Server.js --name zindalern-server
            fi

            pm2 save
          EOF
